### ISSUE TITLE
[csl] clang-format refactoring

### ISSUE THREAD

**Issue by GuillaumeDua** [GuillaumeDua/CppShelf#116]
- Integrates clang-format 16..22 features
- Promote formatting consistency across files
- See [clang-format configuration documentation reference](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)

---
Improve `.clang-format` so that clang-format produces better formatting for the C++ template/concept-heavy code in `includes/mp/csl/mp.hpp`.

**Acceptance criteria:** output should not change much compared to the current state of `includes/mp/csl/mp.hpp`.

## Tasks

- [ ] 1. Namespace bodies start with an empty line
- [ ] 2. Break long template lines — closing `>` on its own line, BlockIndent style
- [ ] 3. Concept clause: break after `=`, break before logical keywords (`and`, `or`)
- [ ] 4. `static_assert` with template args: consistent BlockIndent for `<>`
- [ ] 5. No space between record name and `{}`
- [ ] 6. Break long inheritance / base-class template args
- [ ] 7. Break before `noexcept` and `requires` clause
- [ ] 8. Empty line after `#pragma region`, empty line before `#pragma endregion`
- [ ] 9. Indent preprocessor directive continuation lines
- [ ] 10. Break before IILE in type definitions
- [ ] 11. Break before IILE in concept definitions
- [ ] 12. Break long `static_assert` lines — closing `>` on its own line

---

### 1. Namespace empty line

```cpp
// want
namespace foo {

    template <typename T>
    ...
}
```

### 2. Break long template lines

```cpp
// have
using container = std::unordered_map<std::basic_string<char, std::allocator<char>>, std::array<int, 2>>;

// want
using container = std::unordered_map<
    std::basic_string<
        char,
        std::allocator<char>
    >,
    std::array<int, 2>
>;
```

```cpp
// have
struct make_tuple_storage<std::index_sequence<indexes...>, Ts...> : type_identity<typename mp::details::tuple_storage<mp::details::tuple_member<indexes, Ts>...>> {};

// want
template <std::size_t... indexes, typename... Ts>
struct make_tuple_storage<std::index_sequence<indexes...>, Ts...> : type_identity<
    typename mp::details::tuple_storage<
        mp::details::tuple_member<indexes, Ts>...
    >
>{};
```

```cpp
// have
template <
    concepts::tuple T,
    concepts::tuple U,
    template <typename> class TQual,
    template <typename> class UQual>
struct tuple_common_reference;

template <
    typename... Ts,
    typename... Us,
    template <typename> class TQual,
    template <typename> class UQual>
requires(sizeof...(Ts) == sizeof...(Us))
    and (true and ... and std::common_reference_with<TQual<Ts>, UQual<Us>>)
struct tuple_common_reference<
    tuple<Ts...>,
    tuple<Us...>,
    TQual,
    UQual> {
    using type = tuple<
        std::common_reference_t<
            TQual<Ts>,
            UQual<Us>>...>;
};

// want
template <
    typename... Ts,
    typename... Us,
    template <typename> class TQual,
    template <typename> class UQual
>
requires
        (sizeof...(Ts) == sizeof...(Us))
    and (true and ... and std::common_reference_with<TQual<Ts>, UQual<Us>>)
struct tuple_common_reference<
    tuple<Ts...>, tuple<Us...>,
    TQual, UQual
>
{
    using type = tuple<
        std::common_reference_t<
            TQual<Ts>,
            UQual<Us>
        >...
    >;
};
```

```cpp
// have
template <
    csl::mp::concepts::tuple_like          shape,
    csl::mp::concepts::tuple_like          elements_source,
    csl::mp::seq::concepts::index_sequence index_sequence = std::make_index_sequence<
        std::tuple_size_v<std::remove_cvref_t<elements_source>>>>
struct rebind_N_elements;

// want
template <
    csl::mp::concepts::tuple_like          shape,
    csl::mp::concepts::tuple_like          elements_source,
    csl::mp::seq::concepts::index_sequence index_sequence = std::make_index_sequence<
        std::tuple_size_v<std::remove_cvref_t<elements_source>>
    >
>
struct rebind_N_elements;
```

```cpp
// have
template <csl::mp::concepts::tuple_like shape, csl::mp::concepts::tuple_like elements_source>
struct rebind_elements : rebind_N_elements<shape, elements_source, std::make_index_sequence<std::tuple_size_v<std::remove_cvref_t<elements_source>>>> {};

// want
template <csl::mp::concepts::tuple_like shape, csl::mp::concepts::tuple_like elements_source>
struct rebind_elements : rebind_N_elements<
    shape,
    elements_source,
    std::make_index_sequence<std::tuple_size_v<std::remove_cvref_t<elements_source>>>
>{};
```

### 3. Concept clause alignment

Break after `=`, then each operand on its own line with `and`/`or` at start of line.

```cpp
// have
template <typename T> concept some_concept = true and (not false) and int{} == 0;

// want
template <typename T>
concept some_concept =
        true
    and (not false)
    and int{} == 0
;
```

```cpp
// have
template <typename T, std::size_t N>
concept tuple_element = requires { std::tuple_size<T>{}; }
    and std::tuple_size_v<T> > N and requires(T t) {
            typename std::tuple_element_t<N, std::remove_const_t<T>>;
            { get<N>(t) } -> std::convertible_to<std::tuple_element_t<N, T> &>;
        };

// want
template <typename T, std::size_t N>
concept tuple_element =
        requires { std::tuple_size<T>{}; }
    and std::tuple_size_v<T> > N
    and requires(T t) {
        typename std::tuple_element_t<N, std::remove_const_t<T>>;
        { get<N>(t) } -> std::convertible_to<std::tuple_element_t<N, T>&>;
    }
;
```

### 4. `static_assert` with template args

Same BlockIndent logic as `{}` but for `<>`.

```cpp
// have
static_assert(std::is_same_v<
        csl::mp::tuple<int &&, const char &>,
        decltype(csl::mp::functions::forward_as_tuple(42, c))>);

// want
static_assert(std::is_same_v<
    csl::mp::tuple<int &&, const char &>,
    decltype(csl::mp::functions::forward_as_tuple(42, c))
>);
```

### 5. No space between record name and `{}`

```cpp
// have
struct A : std::type_identity<T> {};

// want
struct A : std::type_identity<T>{};
```

### 6. Break long inheritance lines

```cpp
// have
struct at<index, std::integer_sequence<T, values...>> : std::integral_constant<T, std::get<index>(to_tuplelike_v<std::integer_sequence<T, values...>>)> {};

// want
struct at<index, std::integer_sequence<T, values...>> : std::integral_constant<
    T,
    std::get<index>(to_tuplelike_v<std::integer_sequence<T, values...>>)
>{};
```

### 7. Break before `noexcept` and `requires`

```cpp
// have
constexpr tuple() noexcept((true and ... and std::is_nothrow_constructible_v<Ts>))
requires(true and ... and std::is_default_constructible_v<Ts>)
= default;

// want
constexpr tuple()
noexcept((true and ... and std::is_nothrow_constructible_v<Ts>))
requires (true and ... and std::is_default_constructible_v<Ts>)
= default;
```

```cpp
// have
template <typename... Us>
constexpr explicit(not(true and ... and std::convertible_to<Ts, Us &&>)) tuple(Us &&... args) // NOLINT(*-forward)
    noexcept((std::is_nothrow_constructible_v<Ts, Us &&> and ...))
requires(sizeof...(Ts) not_eq 0) // disambiguate with default constructor
    and (sizeof...(Ts) == sizeof...(Us))
    and (std::constructible_from<Ts, Us &&> and ...)
    : storage{csl_fwd(args)...} {}

// want
template <typename... Us>
explicit(not(
    true and ... and std::convertible_to<Ts, Us &&>
))
constexpr tuple(Us &&... args) // NOLINT(*-forward)
noexcept((std::is_nothrow_constructible_v<Ts, Us &&> and ...))
requires
        (sizeof...(Ts) not_eq 0) // disambiguate with default constructor
    and (sizeof...(Ts) == sizeof...(Us))
    and (std::constructible_from<Ts, Us &&> and ...)
: storage{ csl_fwd(args)... }
{}
```

```cpp
// have
constexpr auto for_each(csl::mp::concepts::tuple_like auto && value, auto && f)noexcept(csl::mp::concepts::can_nothrow_for_each<decltype(value), decltype(f)>)
requires csl::mp::concepts::can_for_each<decltype(value), decltype(f)>
{
    ...
}

// want
constexpr auto for_each(csl::mp::concepts::tuple_like auto && value, auto && f)
noexcept(csl::mp::concepts::can_nothrow_for_each<decltype(value), decltype(f)>)
requires csl::mp::concepts::can_for_each<decltype(value), decltype(f)>
{
    ...
}
```

### 8. Empty lines around `#pragma region` / `#pragma endregion`

```cpp
// want
#pragma region foo

    // ...

#pragma endregion
```

### 9. Indent preprocessor directive continuation lines

```cpp
// have
#if defined(__cpp_explicit_this_parameter) \
    and __cpp_explicit_this_parameter >= 202110L

// want
    #if defined(__cpp_explicit_this_parameter) \
            and __cpp_explicit_this_parameter >= 202110L
```

### 10. Break before IILE in type definitions

```cpp
// have
template <concepts::tuple_like T>
struct is_homogeneous<T> : std::bool_constant<[]<std::size_t... indexes>(std::index_sequence<indexes...>) {
    return (true and ... and std::same_as<csl::mp::element<0, T>, csl::mp::element<indexes, T>>);
}(std::make_index_sequence<csl::mp::size_v<T>>{})> {};

// want
template <concepts::tuple_like T>
struct is_homogeneous<T> : std::bool_constant<
    []<std::size_t... indexes>(std::index_sequence<indexes...>) {
        return (true and ... and std::same_as<element<0, T>, element<indexes, T>>);
    }(std::make_index_sequence<size_v<T>>{})
>{};
```

### 11. Break before IILE in concept definitions

```cpp
// have
template <typename T, typename F>
concept can_for_each = concepts::tuple_like<T> and[]<std::size_t... indexes>(std::index_sequence<indexes...>) {
    return (true and ... and std::is_invocable_v<F, decltype(get<indexes>(std::declval<T>()))>);
}
(std::make_index_sequence<csl::mp::size_v<std::remove_cvref_t<T>>>{});

// want
template <typename T, typename F>
concept can_for_each = concepts::tuple_like<T>
    and []<std::size_t... indexes>(std::index_sequence<indexes...>) {
        return (true and ... and std::is_invocable_v<F, decltype(get<indexes>(std::declval<T>()))>);
    }(std::make_index_sequence<csl::mp::size_v<std::remove_cvref_t<T>>>{});
```

### 12. Break long `static_assert` lines

Same BlockIndent logic for `<>` as for `{}`.

```cpp
// have
static_assert(std::same_as<
        csl::mp::tuple_common_reference_t<
            lhs_t,
            rhs_t,
            std::type_identity_t,
            std::type_identity_t>,
        csl::mp::tuple<
            std::common_reference_t<
                std::tuple_element_t<0, lhs_t>,
                std::tuple_element_t<0, rhs_t>>,
            std::common_reference_t<
                std::tuple_element_t<1, lhs_t>,
                std::tuple_element_t<1, rhs_t>>>>);

// want
static_assert(std::same_as<
    csl::mp::tuple_common_reference_t<
        lhs_t,
        rhs_t,
        std::type_identity_t,
        std::type_identity_t
    >,
    csl::mp::tuple<
        std::common_reference_t<
            std::tuple_element_t<0, lhs_t>,
            std::tuple_element_t<0, rhs_t>
        >,
        std::common_reference_t<
            std::tuple_element_t<1, lhs_t>,
            std::tuple_element_t<1, rhs_t>
        >
    >
>);
```

Short args that fit on one line should stay on one line:

```cpp
// have
static_assert(std::common_reference_with<
        lhs_t,
        rhs_t>);

// want
static_assert(std::common_reference_with<lhs_t, rhs_t>);
```
