### ISSUE TITLE
[ag] `tuple_view` cvref correctness / consistency

### ISSUE THREAD

**Issue by GuillaumeDua** [GuillaumeDua/CppShelf#65]
# [ag] `tuple_view` elements cvref-qualifiers correctness / consistency

Define what's the expected behavior here.

## Questioning

What's semantically are the correct cvref-qualifiers for each elements of a view ?

As-is, `csl::ag` preserve const-correctness, but not necessary ref-correctness.

- Example 1 : misleading ref-qualifier

  ```cpp
  struct S {
          const int & i;
  };
  static_assert(std::same_as<
      decltype(csl::ag::as_tuple_view(std::declval<S>())),
      std::tuple<const int &&> // OK const-correctness preserved,
                                               // but here the rvalue-reference is misleading, as it might denote a potential ownership
  >);
  ```

- Example 2 : misleading const-qualifier discard ?

  ```cpp
  struct S {
      int & i;
  };
  static_assert(std::same_as<
      decltype(csl::ag::as_tuple_view(std::declval<const S>())),
      std::tuple<int &&> // should be `int &` ? `const int &` ?
  >);
  ```

## Todo

- [x] #66 
- [x] #64 
- [x] Fix the code according, considering any behavior delta as a bug
   - [x] Fix `make_field_view`
   - [x] Fix `make_tuple_view`
   - [x] Fix `as_tuple_view_impl<aggregate T>`
- [x] Update tests so they match the new behavior (if so)
- [x] Update examples
- [x] Update the documentation accordingly
- [x] Validate #51

**Comment by GuillaumeDua** [comment]
preserve original type information while not making copies : https://godbolt.org/z/f9x3bMWYe
